name: drawnig_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_drawing_board: ^0.9.3
  # hive_flutter: ^1.1.0
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.4
  photo_manager: ^3.3.0
  # shared_preferences: ^2.3.2
  zoom_tap_animation: ^1.1.0
  json_annotation: 
  intl:
  # calendar_appbar: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: 
  json_serializable: 

flutter:
  uses-material-design: true
